// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPaDc4_QnP6cV1Je4wBc2kIaA0CM4Bp8I',
    appId: '1:268920641222:web:47aee04ceb220c19b8a9c7',
    messagingSenderId: '268920641222',
    projectId: 'imaginetask-engine',
    authDomain: 'imaginetask-engine.firebaseapp.com',
    storageBucket: 'imaginetask-engine.firebasestorage.app',
    measurementId: 'G-CP71ZJ5CYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbLb4f9BEm_qRzcJxOUUbLBV0XEQ2HjfM',
    appId: '1:268920641222:android:ef30ee3c7b45e361b8a9c7',
    messagingSenderId: '268920641222',
    projectId: 'imaginetask-engine',
    storageBucket: 'imaginetask-engine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARP2Qtxt5yTE3n3DQDw1gMTbVrjsMooYQ',
    appId: '1:268920641222:ios:2fb545523534d75fb8a9c7',
    messagingSenderId: '268920641222',
    projectId: 'imaginetask-engine',
    storageBucket: 'imaginetask-engine.firebasestorage.app',
    iosClientId: '268920641222-1b7cc3lbsj2d163dnk7c6mu5f01mleqq.apps.googleusercontent.com',
    iosBundleId: 'com.buildervet.buildervetTemp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARP2Qtxt5yTE3n3DQDw1gMTbVrjsMooYQ',
    appId: '1:268920641222:ios:2fb545523534d75fb8a9c7',
    messagingSenderId: '268920641222',
    projectId: 'imaginetask-engine',
    storageBucket: 'imaginetask-engine.firebasestorage.app',
    iosClientId: '268920641222-1b7cc3lbsj2d163dnk7c6mu5f01mleqq.apps.googleusercontent.com',
    iosBundleId: 'com.buildervet.buildervetTemp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPaDc4_QnP6cV1Je4wBc2kIaA0CM4Bp8I',
    appId: '1:268920641222:web:d768afe67d654494b8a9c7',
    messagingSenderId: '268920641222',
    projectId: 'imaginetask-engine',
    authDomain: 'imaginetask-engine.firebaseapp.com',
    storageBucket: 'imaginetask-engine.firebasestorage.app',
    measurementId: 'G-E0XQ5X3BR0',
  );
}
