import '../../models/country.dart';

class Countries {
  static const List<Country> all = [
    Country(code: 'AE', name: 'United Arab Emirates', languageCode: 'ar'),
    Country(code: 'AR', name: 'Argentina', languageCode: 'es'),
    Country(code: 'AT', name: 'Austria', languageCode: 'de'),
    Country(code: 'AU', name: 'Australia', languageCode: 'en'),
    Country(code: 'BD', name: 'Bangladesh', languageCode: 'bn'),
    Country(code: 'BE', name: 'Belgium', languageCode: 'nl'),
    Country(code: 'BR', name: 'Brazil', languageCode: 'pt'),
    Country(code: 'CA', name: 'Canada', languageCode: 'en'),
    Country(code: 'CH', name: 'Switzerland', languageCode: 'de'),
    Country(code: 'CL', name: 'Chile', languageCode: 'es'),
    Country(code: 'CN', name: 'China', languageCode: 'zh-CN'),
    Country(code: 'CO', name: 'Colombia', languageCode: 'es'),
    Country(code: 'CZ', name: 'Czech Republic', languageCode: 'cs'),
    Country(code: 'DE', name: 'Germany', languageCode: 'de'),
    Country(code: 'DK', name: 'Denmark', languageCode: 'da'),
    Country(code: 'EG', name: 'Egypt', languageCode: 'ar'),
    Country(code: 'ES', name: 'Spain', languageCode: 'es'),
    Country(code: 'FI', name: 'Finland', languageCode: 'fi'),
    Country(code: 'FR', name: 'France', languageCode: 'fr'),
    Country(code: 'GB', name: 'United Kingdom', languageCode: 'en'),
    Country(code: 'GR', name: 'Greece', languageCode: 'el'),
    Country(code: 'HK', name: 'Hong Kong', languageCode: 'zh-TW'),
    Country(code: 'HU', name: 'Hungary', languageCode: 'hu'),
    Country(code: 'ID', name: 'Indonesia', languageCode: 'id'),
    Country(code: 'IE', name: 'Ireland', languageCode: 'en'),
    Country(code: 'IL', name: 'Israel', languageCode: 'he'),
    Country(code: 'IN', name: 'India', languageCode: 'hi'),
    Country(code: 'IR', name: 'Iran', languageCode: 'fa'),
    Country(code: 'IT', name: 'Italy', languageCode: 'it'),
    Country(code: 'JP', name: 'Japan', languageCode: 'ja'),
    Country(code: 'KR', name: 'South Korea', languageCode: 'ko'),
    Country(code: 'MX', name: 'Mexico', languageCode: 'es'),
    Country(code: 'MY', name: 'Malaysia', languageCode: 'ms'),
    Country(code: 'NL', name: 'Netherlands', languageCode: 'nl'),
    Country(code: 'NO', name: 'Norway', languageCode: 'no'),
    Country(code: 'NZ', name: 'New Zealand', languageCode: 'en'),
    Country(code: 'PE', name: 'Peru', languageCode: 'es'),
    Country(code: 'PH', name: 'Philippines', languageCode: 'tl'),
    Country(code: 'PK', name: 'Pakistan', languageCode: 'ur'),
    Country(code: 'PL', name: 'Poland', languageCode: 'pl'),
    Country(code: 'PT', name: 'Portugal', languageCode: 'pt'),
    Country(code: 'RO', name: 'Romania', languageCode: 'ro'),
    Country(code: 'RU', name: 'Russia', languageCode: 'ru'),
    Country(code: 'SA', name: 'Saudi Arabia', languageCode: 'ar'),
    Country(code: 'SE', name: 'Sweden', languageCode: 'sv'),
    Country(code: 'SG', name: 'Singapore', languageCode: 'en'),
    Country(code: 'TH', name: 'Thailand', languageCode: 'th'),
    Country(code: 'TR', name: 'Turkey', languageCode: 'tr'),
    Country(code: 'TW', name: 'Taiwan', languageCode: 'zh-TW'),
    Country(code: 'UA', name: 'Ukraine', languageCode: 'uk'),
    Country(code: 'US', name: 'United States', languageCode: 'en'),
    Country(code: 'VE', name: 'Venezuela', languageCode: 'es'),
    Country(code: 'VN', name: 'Vietnam', languageCode: 'vi'),
    Country(code: 'ZA', name: 'South Africa', languageCode: 'en'),
  ];

  static Map<String, String> get countryToLanguageMap {
    return {for (var c in all) c.code: c.languageCode};
  }
}
